version: "3.3"
services:
  db:
    image: postgres
    environment:
        POSTGRES_USER: foofoo
        POSTGRES_PASSWORD: baz
        POSTGRES_DB: missiontomarsdb  
  m2m:
    build:
        context: .
        dockerfile: Dockerfile
    image: m2m:0.0.1
    environment:
        POSTGRES_USER: foofoo
        POSTGRES_PASSWORD: baz
        POSTGRES_DB: missiontomarsdb
        DB_HOSTNAME: db
        PORT: 5432
    ports:
      - 8080:8080
    depends_on: 
        - "db"

